config/routes.rb
Rails.application.routes.draw do
  get "libcoin_transactions/index"
  get "dashboard/index"
  get "home/index"
  get "images/index"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  get "errors/access_denied", to: "errors#access_denied", as: "access_denied"
  delete "logout", to: "application#sign_out_current_user", as: "logout"
  resources :out_of_context, only: [ :index, :destroy ]
  resources :libcoin_transactions, only: [ :index ]
  resources :high_rollers, only: [ :index ]
  resources :tos, only: [ :index ]
  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "home#index", as: :unauthenticated_root
  end
end

app/controllers/out_of_context_controller.rb
class OutOfContextController < ApplicationController
  before_action :authenticate_user!

  def index
    jwt = PANOPTICON_SERVICE.request_jwt

    response = HTTParty.get(
      "https://panopticon.cacheblasters.com/ooc",
      headers: { "Authorization" => "Bearer #{jwt}" }
    )

    if response.success?
      @ooc_entries = JSON.parse(response.body)
      @ooc_entries = @ooc_entries.sort_by { |entry| entry["dateStored"] }.reverse
      @ooc_entries = @ooc_entries.map { |entry| DISCORD_SERVICE.map_ooc_user_id_to_name(entry, current_user) }
    else
      @ooc_entries = []
      flash[:alert] = "Failed to fetch out-of-context entries."
    end
  end

  def destroy
    if current_user.admin || current_user.owner
      jwt = PANOPTICON_SERVICE.request_jwt
      item_id = params[:id]

      response = HTTParty.delete(
        "https://panopticon.cacheblasters.com/ooc/#{item_id}",
        headers: { "Authorization" => "Bearer #{jwt}" }
      )

      if response.success?
        flash[:notice] = "Item successfully deleted."
      else
        flash[:alert] = "Failed to delete item."
      end

      redirect_to out_of_context_index_path
    end
  end
end

app/helpers/out_of_context_helper.rb
module OutOfContextHelper
end

app/views/out_of_context/index.html.erb
<h1>Out Of Context Images</h1>

<% if @ooc_entries.any? %>
  <div class="ooc-gallery">
    <% @ooc_entries.each do |entry| %>
      <div class="ooc-item">
        <div onclick="openOverlay('<%= entry["imageUrl"] %>')">
          <%= image_tag entry["imageUrl"], alt: "Image for item #{entry["itemID"]}", class: 'ooc-image', loading: 'lazy'%>
        </div>
        <div class="info-bar">
            <% formatted_date = Date.parse(entry["dateStored"]).strftime("%B %d, %Y") %>
            <p><strong><%= entry["itemID"] %></strong> - Reported by <strong><%= entry["display_name"] %></strong> on <strong><%= formatted_date %></strong></p>
        </div>
        <% if current_user.id == entry["reportingUserId"] || current_user.admin || current_user.owner%>
          <%= button_to "Delete", out_of_context_path(entry['itemID']),
                        method: :delete, 
                        data: { turbo_confirm: "Are you sure you want to delete this item (#{entry['itemID']})?" } %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div id="imageOverlay" class="overlay" onclick="closeOverlay()">
    <img id="overlayImage" class="overlay-image" src="" alt="Full Image">
  </div>
<% else %>
  <p>No out-of-context images available.</p>
<% end %>

<script>
function openOverlay(imageUrl) {
  const overlay = document.getElementById('imageOverlay');
  const overlayImage = document.getElementById('overlayImage');
  overlayImage.src = imageUrl;
  overlay.style.display = 'flex';
}

function closeOverlay() {
  const overlay = document.getElementById('imageOverlay');
  overlay.style.display = 'none';
}
</script>